name: warrior_vpn
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  csv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

# Launcher Icon config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/loader.gif
    - assets/shield.png
    - assets/shield.svg
    - assets/shield_back.svg

  fonts:
    - family: Hermit
      fonts:
        - asset: fonts/Hermit-Regular.otf
